#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers
obj-$(CONFIG_SENSORS_AKM8963)	+= ecompass/
obj-$(CONFIG_SENSORS_AL3320A)	+= al3320a/
obj-$(CONFIG_SENSORS_ALS3010)	+= als3010/
obj-$(CONFIG_HALL_SENSOR)       += hall/
obj-$(CONFIG_SENSORS_AK09911)   += akm09911/
obj-$(CONFIG_SENSORS_AP3212C)	+= ap3212c/
obj-$(CONFIG_SENSORS_CAP1106)	+= cap1106/
obj-$(CONFIG_SENSORS_PX3212C)	+= px3212c/
obj-$(CONFIG_SENSORS_KXTJ9)	+= kxtj9/
obj-$(CONFIG_SENSORS_PX3003B)	+= px3003b/
