#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_ME372CL) += simcddrv.o
obj-$(CONFIG_ME372CG) += simcddrv.o
obj-$(CONFIG_ME175CG) += simcddrv2.o
obj-$(CONFIG_PF400CG) += simcddrv2.o
obj-$(CONFIG_A400CG)  += simcddrv2.o
obj-$(CONFIG_A450CG)  += simcddrv2.o
