#ifndef __MICROP_DATA_DEF_H
#define __MICROP_DATA_DEF_H

struct microP_platform_data{
        int intr_gpio;
};

enum MICROP_CMD_ID {
    MICROP_HW_ID=0, // 0x00
    MICROP_LDROM_ID_CODE, // 0x03
    MICROP_ISN, // 0x04
    MICROP_IND_PHONE_READY, // 0x05
    MICROP_POWER_ON_REASON, // 0x07
    MICROP_DISABLE_CHARGING_FOR_FACTORY, // 0x08
    MICROP_CALIBRATION_DATA, // 0x0A
    MICROP_ALWAYS_IGNORE_PHONE_READY, // 0x0B
    MICROP_OEM_SSN,   // 0x0D
    MICROP_OEM_IMEI,	// 0x0E
    MICROP_OEM_FW_VERSION,  // 0x0F
    MICROP_GPIO_INPUT_LEVEL, // 0x20
    MICROP_GPIO_OUTPUT_LEVEL, // 0x21
    MICROP_GPIO_OUTPUT_BIT_SET, // 0x22
    MICROP_GPIO_OUTPUT_BIT_CLR, // 0x23
    MICROP_PAD_HWID,   // 0x26
    MICROP_PROXIM_KDATA, //0x27
    MICROP_CHARGING_STATUS, // 0x30
    MICROP_GAUGE_ID, // 0x31
    MICROP_USB_DET, // 0x34
    MICROP_USB_TYPE,  // 0x37
    MICROP_BATTERY_INFO, // 0x38
    MICROP_BATTERY_SOC, // 0x39
    MICROP_BATTERY_CONFIG, // 0x3A
    MICROP_PWM, // 0x40
    MICROP_INTR_STATUS, // 0x41
    MICROP_INTR_EN, // 0x42
    MICROP_INTR_EN_BIT_SET, // 0x43
    MICROP_INTR_EN_BIT_CLR, // 0x44
    MICROP_BOOT_SELECTION, // 0x50
    MICROP_SET_BOOT_LDROM, // 0x51
    MICROP_SET_BOOT_APROM, // 0x52
    MICROP_APROM_CHECKSUM, // 0x54
    MICROP_SOFTWARE_OFF, // 0x55
    MICROP_IND_PHONE_SLEEP, // 0x56
    MICROP_IND_PHONE_RESUME, // 0x57
    MICROP_OPERATING_STATE, // 0x58
    MICROP_POWER_ON,     //0x5C
    MICROP_MISC_CMD_WOS, // 0x5E
    MICROP_OTG_POWER, // 0x5F
};

enum MICROP_OP_STATE{
    st_MICROP_Off=0,
    st_MICROP_Active=1,
    st_MICROP_Sleep=2,
    st_MICROP_Unknown=3,
};

enum MICROP_POWERON_REASON{
    E_NONE=0,
    E_ON_HS_IN=1,
    E_ON_AC_USB=2,
    E_ON_PWR_KEY_LONGPRESS=3,
};

#define MICROP_RESET_SW_GAUGE      BIT(0)
#define MICROP_RESET_RSOC          BIT(1)
#define MICROP_CLEAR_POWER_REASON  BIT(2)

// define ioctl code
#define ASUS_MICROP_IOC_TYPE    0xa1
#define ASUS_MICROP_FW_UPDATE 	_IOWR(ASUS_MICROP_IOC_TYPE,	1,	int)
#define ASUS_MICROP_CHECK_CONNECTED 	_IOWR(ASUS_MICROP_IOC_TYPE,	2,	int)
#define ASUS_MICROP_GET_FW_VERSION 	_IOWR(ASUS_MICROP_IOC_TYPE,	3,	int)
#define ASUS_MICROP_ON_OFF_GPS_ON_PAD 	_IOWR(ASUS_MICROP_IOC_TYPE,	4,	int)
#define ASUS_MICROP_GET_LDROM_VERSION 	_IOWR(ASUS_MICROP_IOC_TYPE,	5,	int)
#define ASUS_MICROP_GET_PADPHONE_HW_ID 	_IOWR(ASUS_MICROP_IOC_TYPE,	6,	int)
#define ASUS_MICROP_POWER_ON_LED_O	_IOWR(ASUS_MICROP_IOC_TYPE,	7,	int)
#define ASUS_MICROP_POWER_OFF_LED_O	_IOWR(ASUS_MICROP_IOC_TYPE,	8,	int)
#define ASUS_MICROP_POWER_ON_LED_G	_IOWR(ASUS_MICROP_IOC_TYPE,	9,	int)
#define ASUS_MICROP_POWER_OFF_LED_G	_IOWR(ASUS_MICROP_IOC_TYPE,	10,	int)
#define ASUS_MICROP_SEND_VREMOVE_UEVENT	_IOWR(ASUS_MICROP_IOC_TYPE,	11,	int)
#define ASUS_MICROP_PAD_TEST_PLUG_IN_OUT 	_IOWR(ASUS_MICROP_IOC_TYPE,	12,	int)
#define ASUS_MICROP_SEND_CFG_INFO 	_IOWR(ASUS_MICROP_IOC_TYPE,	13,	int)
#define ASUS_MICROP_GET_BATTERY_ID 	_IOWR(ASUS_MICROP_IOC_TYPE,	14,	int)
#define ASUS_MICROP_GET_CONFIG_ID 	_IOWR(ASUS_MICROP_IOC_TYPE,	15,	int)
#define ASUS_MICROP_GET_TS_ID		_IOWR(ASUS_MICROP_IOC_TYPE,     16,     int)
#define ASUS_MICROP_GET_HW_ID		_IOWR(ASUS_MICROP_IOC_TYPE,     17,     uint8_t)
#define ASUS_MICROP_MAX_NR  17

#endif

